name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PackageName: terraform-stripe-provider.tar
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - uses: goreleaser/goreleaser-action@v3
        with:
          args: build --rm-dist --snapshot
          version: latest

      - name: Tar files
        run: tar -cvf $PackageName dist/
