name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - uses: goreleaser/goreleaser-action@v3
        name: Run GoReleaser
        id: goreleaser
        with:
          args: build --clean --snapshot
          version: latest

      - id: packageName
        name: Calculate package name
        run: |
          echo "PACKAGE_NAME=${{ format('{0}_{1}.tar', fromJson(steps.goreleaser.outputs.metadata).project_name, fromJson(steps.goreleaser.outputs.metadata).version) }}" >> "$GITHUB_OUTPUT"

      - name: Tar files
        run: tar -cvf ${{ steps.packageName.output.PACKAGE_NAME }} dist/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.packageName.output.PACKAGE_NAME }}
          path: ${{ steps.packageName.output.PACKAGE_NAME }}